export const SEND_MESSAGE = 'SEND_MESSAGE'

export const GET_ORGANIZATION_LIST_REQUEST = 'GET_ORGANIZATION_LIST_REQUEST'
export const GET_ORGANIZATION_LIST_SUCCESS = 'GET_ORGANIZATION_LIST_SUCCESS'
export const GET_ORGANIZATION_LIST_FAILURE = 'GET_ORGANIZATION_LIST_FAILURE'
